### ISSUE TITLE
[HW5] Homework 5 - Game AI, Visual Effect

### ISSUE THREAD

**Issue by leehe228** [leehe228/Game-Programming-KU#11]
## Objective

Improve the Game Al and Visual Effects in Your Shooting Game

## Tasks

- Extend your game from HW4 project
- Visual Effects
    - [ ]  Introduce new visual effects in the Scene
    - [ ]  Introduce new visual effects for the player or enemies
    - [ ]  The visual effects must be created using a Shader Graph, Particle System, or Visual Effect Graph
    - [ ]  Please use at least two methods mentioned above for your visual effects
- Game AI
    - [ ]  Improve the FSM for enemies
        
        → The enemies should aim to kill the player or destroy the main base
        
    - [ ]  Introduce new features of your own design
        
        → It's acceptable to extend the game logic or add more features
        

## Requirements

- Avoid using external assets when creating new visual effects
    - It is acceptable to use external textures of materials
- Avoid replicating methods used in the textbook to create visual effects for objects featured in the textbook
    - Do not utilize the shader graph for creating water effects
    - If you intend to create a waterfall or bone fire effect, refrain from using the Shuriken particle system
    - For rain effects, use methods other than the visual effect graph
- There will be no penalties for Korean presentation
    - All slides must be written in English
- Ensure that your FSM must be different from the one presented in the textbook

## Submission Guidelines

- Submit the presentation video (< 7 minutes) to E-Campus
    - Please do not use any external link for the video submission
    - Explain your gameplay recording
    - Describe the new visual effects in your game
        - Explain the method in brief
    - Describe the Game Al of your game
        - Explain the FSM as a diagram
- Submit the link to your Github Repository
    - Ensure that the same requirements as in HW1 are met
